
```{r}
library(ggplot2)
library(gridExtra)
library(tidymodels)
```

```{r}
#Importing X data
X=as.matrix(read.csv(file="D:\\EEG DATA\\X_data.csv",header = F))
colnames(X)<-c("X1","X2","X3","X4")
```

```{r}
#Importing Y data
Y=as.matrix(read.csv(file="D:\\EEG DATA\\Y_data.csv",header = F))
colnames(Y)<-c("Y")
```

```{r}
#Importing Time data
Time=read.csv(file="D:\\EEG DATA\\Time_data.csv",header = F,skip=1)
Time=as.matrix(rbind(0,Time))
```


```{r}
#Task 1
#Creating a time series plot
X.timeseries=ts(X,start=c(min(Time),max(Time)),frequency=1)
Y.timeseries=ts(Y,start=c(min(Time),max(Time)),frequency=1)
```


```{r}
# Plotting the time series graph
# Merge all Input Signals Plot of X series 
# X1 series plot
x1_plot<-ggplot(data.frame(X.timeseries), aes(x=Time, y=X1)) +
  geom_line(color='#165CAA',size=1) +
  ylab("X1") +
  theme(legend.position="right")

# X2 series plot
x2_plot<-ggplot(data.frame(X.timeseries), aes(x=Time, y=X2)) +
  geom_line(color='red',size=1) +
  ylab("X2") +
  theme(legend.position="right")

# X3 series plot
x3_plot<-ggplot(data.frame(X.timeseries), aes(x=Time, y=X3)) +
  geom_line(color='orange',size=1) +
  theme(legend.position="right")

# X4 series plot
x4_plot<-ggplot(data.frame(X.timeseries), aes(x=Time, y=X4)) +
  geom_line() +
  theme(legend.position="right")

library(gridExtra)
grid.arrange(x1_plot, x2_plot, x3_plot, x4_plot, nrow = 4, ncol = 1, top = "Time Series Plot of X Signals")

```

```{r}
# Plotting the time series graph
# X series plot
# X1 series plot
ggplot(data.frame(X.timeseries), aes(x=Time, y=X1)) +
  geom_line(color='#165CAA',size=1) +
  ggtitle("Time series plot of X1 Signal") +
  xlab("Time") +
  ylab("Input Signal X1") +
  theme(legend.position="right")

# X2 series plot
ggplot(data.frame(X.timeseries), aes(x=Time, y=X2)) +
  geom_line(color='red',size=1) +
  ggtitle("Time series plot of X2 Signal") +
  xlab("Time") +
  ylab("Input Signal X2") +
  theme(legend.position="right")

# X3 series plot
ggplot(data.frame(X.timeseries), aes(x=Time, y=X3)) +
  geom_line(color='orange',size=1) +
  ggtitle("Time series plot of X3 Signal") +
  xlab("Time") +
  ylab("Input Signal X3") +
  theme(legend.position="right")

# X4 series plot
ggplot(data.frame(X.timeseries), aes(x=Time, y=X4)) +
  geom_line() +
  ggtitle("Time series plot of X4 Signal") +
  xlab("Time") +
  ylab("Input Signal X4") +
  theme(legend.position="right")

#Y series plot
ggplot(data.frame(Y.timeseries), aes(x=Time, y=Y)) +
  geom_line(color='indianred',size=1) +
  ggtitle("Time series plot of Y Signal") +
  xlab("Time") +
  ylab("Output Signal")

```

```{r}
data_frame =  data.frame(cbind(X,Y,Time))
```


```{r}
#For Input Signals 'X'
x_density=density(X)
# Create data frame for plotting
density_df <- data.frame(x=x_density$x, y=x_density$y)

# Density Plot of whole input signals 'X'
ggplot(density_df, aes(x,y)) +
  geom_line(color="orangered",size=1) +
  ggtitle("Density Plot of Whole Input Signals 'X'") +
  xlab("Density Plot of Input Signal") +
  ylab("Density") +
  theme_grey()

# Histogram with Density Plot
#X1 Signal 
ggplot(data_frame, aes(x = X1)) +    
  ggtitle("Histogram with Density Plot of X1 Signal with Rug") +
  geom_histogram(aes(y = ..density..), bins=10,fill = "darkolivegreen3",color='darkolivegreen') +
  geom_rug(na.rm = FALSE) +
  stat_density(geom="line",col='orangered',size=1) +
  xlab("X1 Signal") +
  ylab("Density")
  
#X2 Signal  
ggplot(data_frame, aes(x = X2)) +    
  ggtitle("Histogram with Density Plot of X2 Signal with Rug") +
  geom_histogram(aes(y = ..density..), bins=10,fill = "cornsilk",color='darkolivegreen') +
  geom_rug(na.rm = FALSE) +
  stat_density(geom="line",col='orangered',size=1) +
  xlab("X2 Signal") +
  ylab("Density")
  
#X3 Signal
ggplot(data_frame, aes(x = X3)) +    
  ggtitle("Histogram with Density Plot of X3 Signal with Rug") +
  geom_histogram(aes(y = ..density..), bins=10,fill = "mistyrose2",color='darkolivegreen') +
  geom_rug(na.rm = FALSE) +
  stat_density(geom="line",col='orangered',size=1) +
  xlab("X3 Signal") +
  ylab("Density")
  
#X4 Signal
ggplot(data_frame, aes(x = X4)) +    
  ggtitle("Histogram with Density Plot of X4 Signal with Rug") +
  geom_histogram(aes(y = ..density..), bins=10,fill = "slategray2",color='darkolivegreen') +
  geom_rug(na.rm = FALSE) +
  stat_density(geom="line",col='orangered',size=1) +
  xlab("X4 Signal") +
  ylab("Density")
  
#For Output Signal 'Y'
y_density=density(Y)
df <- data.frame(x = y_density$x, y = y_density$y)

#Density Plot of Y Signal
ggplot(df, aes(x, y)) +
  geom_line(color = "red",size=1) +
  ggtitle("Density Plot of Y Signal") +
  xlab("Density Plot of Output Signal") +
  ylab("Density") +
  theme_grey()

#Histogram with Density Plot
ggplot(data_frame, aes(x = Y)) +    
  ggtitle("Histogram with Density Plot of Y Signal") +
  geom_histogram(aes(y = ..density..), bins=10,fill = "goldenrod1",color='goldenrod4') +
  geom_rug(na.rm = FALSE) +
  stat_density(geom="line",col='orangered',size=1) +
  xlab("Y Signal") +
  ylab("Density")
  
```


```{r}
# Correlation and scatter plots 
# X1 Signal
ggplot(data.frame(X[,"X1"], Y), aes(X[,"X1"], Y)) +
  geom_point(col='orange') +
  ggtitle("Correlation Between X1 and Y Signal") +
  xlab("X1 Signal") +
  ylab("Output Signal")

# X2 Signal
ggplot(data.frame(X[,"X2"], Y), aes(X[,"X2"], Y)) +
  geom_point(col='red') +
  ggtitle("Correlation Between X2 and Y Signal") +
  xlab("X2 Signal") +
  ylab("Output Signal")

# X3 Signal
ggplot(data.frame(X[,"X3"], Y), aes(X[,"X3"], Y)) +
  geom_point(col='blue') +
  ggtitle("Correlation Between X3 and Y Signal") +
  xlab("X3 Signal") +
  ylab("Output Signal")

# X4 Signal
ggplot(data.frame(X[,"X4"], Y), aes(X[,"X4"], Y)) +
  geom_point(col='seagreen4') +
  ggtitle("Correlation Between X4 and Y Signal") +
  xlab("X4 Signal") +
  ylab("Output Signal")

```
```{r}
# Task 2: Regression – modeling the relationship between EEG signals 
#Calculating Ones for Binding the data

# Task 2.1
ones=matrix(1,length(X)/4,1)
# Adding a random noise to the data set
noise <- rnorm(length(data_frame$Y), mean = 0, sd = 0.1)
```

```{r}
#Binding data from equation of candidate models and calculate their respective theta hat
X_model_1=cbind(data_frame$X4,data_frame$X1^2,data_frame$X1^3,data_frame$X2^4,data_frame$X1^4,ones,noise)
Model_1_theta_hat=solve(t(X_model_1) %*% X_model_1) %*% t(X_model_1) %*% Y
Model_1_theta_hat

X_model_2=cbind(data_frame$X4,data_frame$X1^3,data_frame$X3^4,ones,noise)
Model_2_theta_hat=solve(t(X_model_2) %*% X_model_2) %*% t(X_model_2) %*% Y
Model_2_theta_hat

X_model_3=cbind(data_frame$X3^3,data_frame$X3^4,ones,noise)
Model_3_theta_hat=solve(t(X_model_3) %*% X_model_3) %*% t(X_model_3) %*% Y
Model_3_theta_hat

X_model_4=cbind(data_frame$X2,data_frame$X1^3,data_frame$X3^4,ones,noise)
Model_4_theta_hat=solve(t(X_model_4) %*% X_model_4) %*% t(X_model_4) %*% Y
Model_4_theta_hat

X_model_5=cbind(data_frame$X4,data_frame$X1^2,data_frame$X1^3,data_frame$X3^4,ones,noise)
Model_5_theta_hat=solve(t(X_model_5) %*% X_model_5) %*% t(X_model_5) %*% Y
Model_5_theta_hat
```

```{r}
# Task 2.2
#Calculating Y-hat and RSS of each candidate model
Y_hat_m1 = X_model_1 %*% Model_1_theta_hat
RSS_Model_1=sum((data_frame$Y-Y_hat_m1)^2)
RSS_Model_1

Y_hat_m2 = X_model_2 %*% Model_2_theta_hat
RSS_Model_2=sum((data_frame$Y-Y_hat_m2)^2)
RSS_Model_2

Y_hat_m3 = X_model_3 %*% Model_3_theta_hat
RSS_Model_3=sum((data_frame$Y-Y_hat_m3)^2)
RSS_Model_3

Y_hat_m4 = X_model_4 %*% Model_4_theta_hat
RSS_Model_4=sum((data_frame$Y-Y_hat_m4)^2)
RSS_Model_4

Y_hat_m5 = X_model_5 %*% Model_5_theta_hat
RSS_Model_5=sum((data_frame$Y-Y_hat_m5)^2)
RSS_Model_5

```
```{r}
### Task 2.3 Calculating likelihood and Variance of each model
#Calculating the length of matrix Y
N=length(data_frame$Y)

# Calculating the Variance and likelihood of each candidate model 
# Model 1
variance_model_1=RSS_Model_1/(N-1)
variance_model_1
likelihood_model_1= -(N/2)*(log(2*pi))-(N/2)*(log(variance_model_1))-(1/(2*variance_model_1))*RSS_Model_1

likelihood_model_1
# Model 2
variance_model_2=RSS_Model_2/(N-1)
variance_model_2
likelihood_model_2= -(N/2)*(log(2*pi))-(N/2)*(log(variance_model_2))-(1/(2*variance_model_2))*RSS_Model_2
likelihood_model_2

#Model 3
variance_model_3=RSS_Model_3/(N-1)
variance_model_3
likelihood_model_3= -(N/2)*(log(2*pi))-(N/2)*(log(variance_model_3))-(1/(2*variance_model_3))*RSS_Model_3
likelihood_model_3

#Model 4
variance_model_4=RSS_Model_4/(N-1)
variance_model_4
likelihood_model_4= -(N/2)*(log(2*pi))-(N/2)*(log(variance_model_4))-(1/(2*variance_model_4))*RSS_Model_4
likelihood_model_4

#Model 5
variance_model_5=RSS_Model_5/(N-1)
variance_model_5
likelihood_model_5= -(N/2)*(log(2*pi))-(N/2)*(log(variance_model_5))-(1/(2*variance_model_5))*RSS_Model_5
likelihood_model_5
```
```{r}
variance_model_1
variance_model_2
variance_model_3
variance_model_4
variance_model_5
```

```{r}
#Task 2.4
##Calculating AIC and BIC of each candidate model
# Model 1
K_model_1<-length(Model_1_theta_hat)
AIC_model_1=2*K_model_1-2*likelihood_model_1
BIC_model_1=K_model_1*log(N)-2*likelihood_model_1
print("Model 1")
AIC_model_1
BIC_model_1

# Model 2
K_model_2<-length(Model_2_theta_hat)
AIC_model_2=2*K_model_2-2*likelihood_model_2
BIC_model_2=K_model_2*log(N)-2*likelihood_model_2
print("Model 2")
AIC_model_2
BIC_model_2

# Model 3
K_model_3<-length(Model_3_theta_hat)
AIC_model_3=2*K_model_3-2*likelihood_model_3
BIC_model_3=K_model_3*log(N)-2*likelihood_model_3
print("Model 3")
AIC_model_3
BIC_model_3

# Model 4
K_model_4<-length(Model_4_theta_hat)
AIC_model_4=2*K_model_4-2*likelihood_model_4
BIC_model_4=K_model_4*log(N)-2*likelihood_model_4
print("Model 4")
AIC_model_4
BIC_model_4

# Model 5
K_model_5<-length(Model_5_theta_hat)
AIC_model_5=2*K_model_5-2*likelihood_model_5
BIC_model_5=K_model_5*log(N)-2*likelihood_model_5
print("Model 5")
AIC_model_5
BIC_model_5
```

```{r}
## Task 2.5
##Error
# Distribution of model prediction errors (residuals) for each candidate model
library(ggplot2)
model_1_error <- data_frame$Y-Y_hat_m1
model_2_error <- data_frame$Y-Y_hat_m2
model_3_error <- data_frame$Y-Y_hat_m3
model_4_error <- data_frame$Y-Y_hat_m4
model_5_error <- data_frame$Y-Y_hat_m5

# Creating error data frame
error_data_frame=data.frame(cbind(model_1_error,model_2_error,model_3_error,model_4_error,model_5_error))

## Plotting the graph Q-Q plot and QQ line of model
# Model 1 Error
ggplot(error_data_frame, aes(sample = model_1_error)) + 
  geom_qq(color='cadetblue') + 
  geom_qq_line(color = "firebrick3",linewidth=0.5) +
  ggtitle("QQ plot of model 1") +
  scale_color_manual(values = c("firebrick3" = "firebrick3"))

# Model 2 Error
ggplot(error_data_frame, aes(sample = model_2_error)) + 
  geom_qq(color='darkgoldenrod1') + 
  geom_qq_line(color = "firebrick3",linewidth=0.5) +
  ggtitle("QQ plot of model 2") +
  scale_color_manual(values = c("firebrick3" = "firebrick3"))

# Model 3 Error
ggplot(error_data_frame, aes(sample = model_3_error)) + 
  geom_qq(color='darkgray') + 
  geom_qq_line(color = "firebrick3",linewidth=0.5) +
  ggtitle("QQ plot of model 3") +
  scale_color_manual(values = c("firebrick3" = "firebrick3"))

# Model 4 Error
ggplot(error_data_frame, aes(sample = model_4_error)) + 
  geom_qq(color='royalblue4') + 
  geom_qq_line(color = "firebrick3",linewidth=0.5) +
  ggtitle("QQ plot of model 4") +
  scale_color_manual(values = c("firebrick3" = "firebrick3"))

# Model 5 Error
ggplot(error_data_frame, aes(sample = model_5_error)) + 
  geom_qq(color='darkgreen') + 
  geom_qq_line(color = "firebrick3",linewidth=0.5) +
  ggtitle("QQ plot of model 5") +
  scale_color_manual(values = c("firebrick3" = "firebrick3"))

```
```{r}
### Task 2.7
library(tidymodels)
tidymodels_prefer()

split_data = initial_split(data_frame, prop = .7)
training_set = training(split_data)
testing_set = testing(split_data)

# Testing set
test_noise <- rnorm(length(testing_set$X1), mean = 0, sd = 0.1)

### Estimating model parameters using training set
testing_ones=matrix(1 , length(testing_set$X1),1)
X_testing_model<-cbind(testing_ones,testing_set$X4,(testing_set$X1)^3,(testing_set$X3)^4,test_noise)
testing_theta_hat = solve(t(X_testing_model) %*% X_testing_model) %*% t(X_testing_model) %*% testing_set$Y

# Training set
train_noise <- rnorm(training_set$X1, mean = 0, sd = 0.1)
training_ones=matrix(1 , length(training_set$X1),1)
X_training_model<-cbind(training_ones,training_set$X4,(training_set$X1)^3,(training_set$X3)^4,train_noise)
training_theta_hat = solve(t(X_training_model) %*% X_training_model) %*% t(X_training_model) %*% training_set$Y


Y_testing_hat = X_testing_model %*% testing_theta_hat
Y_training_hat = X_training_model %*% training_theta_hat

conf_interval = t.test(Y_training_hat, Y_testing_hat, mu = 500, alternative = "two.sided", conf.level=0.95)
conf_interval

C_I1 = conf_interval$conf.int[1]
C_I2 = conf_interval$conf.int[2]
S_ERROR = conf_interval$stderr

ggplot(training_set, aes(x = Y)) +    # Draw histogram & density
  geom_density(fill = "cadetblue", color = "cadetblue", alpha = 0.5) +
  geom_vline(xintercept = C_I1, linetype="dashed", color="red",size=0.5)+
  geom_vline(xintercept = C_I2, linetype="dashed", color="red",size=0.5)+
  geom_vline(xintercept = S_ERROR, linetype="dashed", color="black",size=0.5)+
  ggtitle("Distribution of training Data") +
  xlab("Training data") +
  ylab("Density")

ggplot(testing_set, aes(x = Y)) +    # Draw histogram & density
  geom_density(fill = "orange", color = "orange", alpha = 0.5) +
  geom_vline(xintercept = C_I1, linetype="dashed", color="red",size=0.5)+
  geom_vline(xintercept = C_I2, linetype="dashed", color="red",size=0.5)+
  geom_vline(xintercept = S_ERROR, linetype="dashed", color="black",size=0.5)+
  ggtitle("Distribution of testing Data") +
  xlab("Testing data") +
  ylab("Density")

```

```{r}
# Task 3
arr_1=0
arr_2=0
f_value=0
s_value=0

#Model parameters of the chosen model
theta_bias <- Model_2_theta_hat[4,] 
theta_one <- Model_2_theta_hat[1,]
theta_two <- Model_2_theta_hat[2,]
theta_three <- -Model_2_theta_hat[3,]
theta_noise <- Model_2_theta_hat[5,]

epsilon <- RSS_Model_2 * 2
num <- 100

counter <- 0
for (i in 1:num) {
  r1 <- runif(1,-abs(theta_bias),abs(theta_bias))
  r2 <- runif(1,-abs(theta_one), abs(theta_one))
  new_theta_hat <- matrix(c(r1,r2,theta_two,theta_three, theta_noise))
  new_Y_Hat <- X_model_2 %*% new_theta_hat ## New Y hat
  new_RSS <- sum((data_frame$Y-new_Y_Hat)^2)
 
  if (new_RSS > epsilon){
    arr_1[i] <- r1
    arr_2[i] <- r2
    counter = counter+1
    f_value <- matrix(arr_1)
    s_value <- matrix(arr_2)
  }
}
hist(f_value)
hist(s_value)
###ploting the graph

df <- data.frame(f_value, s_value, col = c("orangered", "darkgreen"))
ggplot(df, aes(f_value, s_value, color = col)) + 
  geom_point() +
  ggtitle("Joint and Marginal Posterior Distribution")

```

